# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f25fe1f9-74a6-46ef-a948-b56f39ea46de";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8F7D-BDEB";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/Gondoline" =
    { device = "/dev/disk/by-uuid/87abd77b-5ad5-4444-8046-a23d14418f12";
      fsType = "xfs";
    };

  fileSystems."/mnt/Erebor/Thorin" =
    { device = "/dev/disk/by-uuid/89c844a1-0b1f-454f-8750-121d71c16f12";
      fsType = "ext4";
    };

  fileSystems."/mnt/Erebor/Dain" =
    { device = "/dev/disk/by-uuid/8ab6455d-05eb-4f81-b29d-80eb3d57f9ad";
      fsType = "ext4";
    };

  fileSystems."/mnt/Erebor/War-goats" =
    { device = "/dev/disk/by-uuid/0871cc76-6439-49cc-8f8f-566be2b79df4";
      fsType = "ext4";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
