width = 40%
height = 40%
anchor = center
corner-radius = 10

border-width = 1
border-color = #b1bef0

outline-width = 0

background-color = #000000a1

result-spacing = 25

padding-left = 7%
padding-top = 9%

font = FiraCode Nerd Font
prompt-text = "Screenshot: "
